language: python
python:
  - "2.6"
  - "2.7"

# install dependencies
before_install:
  - sudo apt-get install python-dev
  - sudo apt-get install libboost-dev
  - sudo apt-get install libboost-python-dev

# build script
install: python setup.py build

# run tests
script: nosetests
